pipeline:
  identifier: Build_ericmittelhammer_spring_petclinic_1780226367800
  name: Build spring-petclinic
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Plugin
                  name: copyDependencies
                  identifier: copyDependencies
                  spec:
                    connectorRef: account.harnessImage
                    image: kameshsampath/drone-java-maven-plugin
                    settings:
                      goals:
                        - clean
                        - package
                        - dependency:copy-dependencies
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1780225992389
        repoName: ericmittelhammer/spring-petclinic
        build: <+input>
