pipeline:
  identifier: Build_ericmittelhammer_spring_petclinic_1780226367800
  name: Build spring-petclinic
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: maven:3.8-jdk-11
                connectorRef: account.docker_hardened
          execution:
            steps:
              - step:
                  type: Run
                  name: Check Dependencies
                  identifier: Check_Dependencies
                  spec:
                    shell: Sh
                    command: mvn clean package dependency:copy-dependencies
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1780225992389
        repoName: ericmittelhammer/spring-petclinic
        build: <+input>
