pipeline:
  identifier: Build_ericmittelhammer_spring_petclinic_1780226367800
  name: Build spring-petclinic
  orgIdentifier: default
  projectIdentifier: default_project
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Compile
                  identifier: Compile
                  spec:
                    shell: Sh
                    command: ./gradlew compileJava --no-daemon
                contextType: Pipeline
              - parallel:
                  - step:
                      type: Run
                      name: Test
                      identifier: Test
                      spec:
                        shell: Sh
                        command: ./gradlew test --no-daemon
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - "**/build/test-results/test/*.xml"
                  - step:
                      type: Run
                      name: Checkstyle
                      identifier: Checkstyle
                      spec:
                        shell: Sh
                        command: ./gradlew checkstyleMain --no-daemon
                      failureStrategies:
                        - onFailure:
                            errors:
                              - AllErrors
                            action:
                              type: Ignore
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push Image
                  identifier: Build_and_Push_Image
                  spec:
                    connectorRef: account.Docker_Hub
                    repo: ericmittelhammer/petclinic
                    tags:
                      - latest
                      - <+pipeline.sequenceId>
                    caching: true
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Petclinic
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      sources:
                        - identifier: PetclinicImage
                          type: DockerRegistry
                          spec:
                            tag: <+input>
                      primaryArtifactRef: petclinic
          environment:
            environmentRef: Harness_Lab_Cluster_EKS
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Harness_Lab_EKS
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDeployment
                  steps:
                    - step:
                        name: Canary Deployment
                        identifier: canaryDeployment
                        type: K8sCanaryDeploy
                        timeout: 10m
                        spec:
                          instanceSelection:
                            type: Count
                            spec:
                              count: 1
                          skipDryRun: false
                    - step:
                        name: Canary Delete
                        identifier: canaryDelete
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDeployment
                  steps:
                    - step:
                        name: Rolling Deployment
                        identifier: rollingDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
            rollbackSteps:
              - step:
                  name: Canary Delete
                  identifier: rollbackCanaryDelete
                  type: K8sCanaryDelete
                  timeout: 10m
                  spec: {}
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1780225992389
        repoName: ericmittelhammer/spring-petclinic
        build: <+input>
